# Generated by Django 4.2.7 on 2023-11-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_define_exams_related_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('M', 'Féminin')], max_length=1, null=True),
        ),
    ]
