# Generated by Django 4.2.7 on 2023-11-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='bourse',
            field=models.BooleanField(default=False, verbose_name='bourse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('M', 'Féminin')], default='M', max_length=1, null=True, verbose_name='sexe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='prénoms'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.level', verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='student',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.option', verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.schoolyear'),
        ),
    ]
